"""
trend_fetcher.py — Cluster-aware Trending Topic Fetcher v4 (Consumer)
=====================================================================
Strategy:
  - This file is now a pure consumer.
  - It reads pre-vetted, high-quality topics generated by `trend_harvester.py`.
  - It pops a single topic from the `assets/config/curated_trends.json` file.
  - It guarantees zero duplicates and zero API calls during the main pipeline run.

Usage:
    from pipeline.trend_fetcher import get_trending_topic
    topic = get_trending_topic(seen_topics, cluster="VIRAL_FACTS_1")
"""

from __future__ import annotations

import logging
import os
import json
from typing import Optional, Set

log = logging.getLogger("pipeline.trend_fetcher")

CURATED_FILE = os.path.join("assets", "config", "curated_trends.json")

def _load_curated_trends() -> dict[str, list[str]]:
    if not os.path.exists(CURATED_FILE):
        log.warning(f"Curated trends file missing: {CURATED_FILE}. Please run trend_harvester.py first.")
        return {}
    try:
        with open(CURATED_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        log.error(f"Failed to parse {CURATED_FILE}: {e}")
        return {}

def _save_curated_trends(data: dict[str, list[str]]):
    try:
        os.makedirs(os.path.dirname(CURATED_FILE), exist_ok=True)
        with open(CURATED_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
    except Exception as e:
        log.error(f"Failed to save {CURATED_FILE}: {e}")

def get_trending_topic(seen: set[str], cluster: str = "SCIENCE") -> str:
    """
    Return a fresh, pre-vetted topic string for the given niche cluster.
    """
    log.info(f"[trend_fetcher] Fetching pre-vetted topic for cluster: {cluster}")
    
    curated_data = _load_curated_trends()
    cluster_topics = curated_data.get(cluster, [])
    
    if not cluster_topics:
        raise RuntimeError(
            f"Topic pool exhausted for cluster {cluster!r}.\n"
            f"The Trend Harvester must be run to replenish the pool.\n"
            f"Run: python trend_harvester.py"
        )

    # Convert seen to lowercase for robust matching
    seen_lower = {s.lower().strip() for s in seen}
    
    topic_to_use = None
    topics_to_keep = []
    
    # Iterate through the pool to find the first unused topic
    for i, topic in enumerate(cluster_topics):
        if not topic_to_use and topic.lower().strip() not in seen_lower:
            topic_to_use = topic
            # We skip this index for topics_to_keep because we are consuming it
            topics_to_keep.extend(cluster_topics[i+1:])
            break
        else:
            # We keep it because it was already seen (and will be skipped later, or we haven't found a match yet)
            # Actually, if it's in seen, we should probably discard it to clean the file.
            if topic.lower().strip() not in seen_lower:
                 topics_to_keep.append(topic)

    if not topic_to_use:
        # All topics in the file have been seen! Clear the list and crash.
        curated_data[cluster] = []
        _save_curated_trends(curated_data)
        raise RuntimeError(f"All pre-vetted topics for cluster {cluster!r} have already been used. Run trend_harvester.py.")

    # Save the updated list back to disk, minus the consumed topic and any seen junk
    curated_data[cluster] = topics_to_keep
    _save_curated_trends(curated_data)
    
    log.info(f"[trend_fetcher] Consumed topic: {topic_to_use!r}. {len(topics_to_keep)} remaining in pool.")
    return topic_to_use